version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node
    steps:
        - checkout
        - run: gem install bundler:1.17.2
        - run: bundle install
        - run: npm install
        - run: bundle exec jekyll contentful
        - run: gulp deploy