version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-jessie
    dependencies:
      pre:
        - gem install bundler
    steps:
        - checkout
        - run: bundle install
        - run: npm install
        - run: bundle exec jekyll contentful
        - run: gulp deploy